# Generated by Django 5.2.5 on 2025-08-23 09:35

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reservations', '0001_initial'),
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actual_check_in_time', models.DateTimeField()),
                ('adults_count', models.PositiveIntegerField(blank=True, null=True)),
                ('children_count', models.PositiveIntegerField(default=0)),
                ('identity_verified', models.BooleanField(default=True)),
                ('verified_by', models.CharField(blank=True, max_length=100, null=True)),
                ('deposit_paid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('early_checkin_charge', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('number_of_keys', models.PositiveIntegerField(default=1)),
                ('special_requests_fulfilled', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reservation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='checkin', to='reservations.reservation')),
            ],
            options={
                'verbose_name': 'Check In',
                'verbose_name_plural': 'Check Ins',
            },
        ),
        migrations.CreateModel(
            name='CheckOut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actual_check_out_time', models.DateTimeField()),
                ('final_bill_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('payment_status', models.CharField(choices=[('PENDING', 'Pending Payment'), ('PAID', 'Fully Paid'), ('PARTIAL', 'Partially Paid'), ('REFUNDED', 'Refunded')], default='PENDING', max_length=20)),
                ('late_checkout_charge', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('damage_charge', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('room_condition', models.CharField(choices=[('CLEAN', 'Clean'), ('NEEDS_CLEANING', 'Needs Cleaning'), ('MAINTENANCE_REQUIRED', 'Maintenance Required'), ('DAMAGED', 'Damaged')], default='CLEAN', max_length=30)),
                ('minibar_charges', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('phone_charges', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('other_charges', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('processed_by', models.CharField(blank=True, max_length=100, null=True)),
                ('feedback_rating', models.PositiveIntegerField(blank=True, null=True)),
                ('feedback_comment', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('check_in', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='checkout', to='checkin.checkin')),
            ],
            options={
                'verbose_name': 'Check Out',
                'verbose_name_plural': 'Check Outs',
            },
        ),
        migrations.CreateModel(
            name='RoomKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_code', models.CharField(max_length=50, unique=True)),
                ('key_type', models.CharField(choices=[('PHYSICAL', 'Physical Key'), ('RFID', 'RFID Card'), ('MAGNETIC', 'Magnetic Card'), ('DIGITAL', 'Digital/Mobile Key')], default='RFID', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('deactivated_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('check_in', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keys', to='checkin.checkin')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooms.room')),
            ],
            options={
                'verbose_name': 'Room Key',
                'verbose_name_plural': 'Room Keys',
            },
        ),
    ]
